apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/angryscorp/momo-store.git
    targetRevision: main
    path: deploy/charts/backend
    helm:
      releaseName: production-backend
      valueFiles:
        - ../../envs/production/backend-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    syncOptions:
      # ServiceMonitor CRD is installed by the monitoring Application.
      - SkipDryRunOnMissingResource=true
