apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/angryscorp/momo-store.git
    targetRevision: main
    path: deploy/charts/backend
    helm:
      releaseName: staging-backend
      valueFiles:
        - ../../envs/staging/backend-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
